# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  lution = {
    pname = "lution";
    version = "stable-v0.3.2";
    src = fetchFromGitHub {
      owner = "Wookhq";
      repo = "Lution";
      rev = "stable-v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-A0o7o+zoVVxnODO6P+kKHyhGwxDRbPfKd6Y6W+6ivNY=";
    };
  };
}
